spring:
    datasource:
      url: jdbc:mysql://119.28.179.36:3306/Test?autoReconnect=true&useSSL=false&characterEncoding=utf-8
      username: root
      password: xiangjianjian
      driver-class-name: com.mysql.jdbc.Driver

upload_folder: /home/